season_spring_btn = '▫️Весенний сезон'
season_summer_btn = '▫️Летний сезон'
season_autumn_btn = '▫️Осенний сезон'
season_winter_btn = '▫️Зимний сезон'
last_month_btn = '▫️Прошлый месяц'
last_year_btn = '▫️Прошлый год'